"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//
import Navigation from "@/layout/Navigation";
import Header from "@/layout/Header";
import TopLeftImg from "@/layout/TopLeftImg";
//
import { useRouter, usePathname } from "next/navigation";
//
import AnimationWrapper from "@/layout/AnimationWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brian' website",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  console.log(pathName);
  console.log("rander layout");
  return (
    <html lang="en">
      <body
        className={`${inter.className} page bg-site text-white bg-cover bg-no-repeat relative`}
      >
        <TopLeftImg />
        <Navigation />
        <Header />
        <AnimationWrapper>{children}</AnimationWrapper>
      </body>
    </html>
  );
}
